import { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Sunny Meadow',
    subtitle: 'Learn the ropes & create juicy combos!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'orange'],
    maxMoves: 18,
    targetScore: 1800,
    targetType: 'score',
    starThresholds: [1800, 2500, 3400],
  },
  {
    id: 2,
    name: 'Pastel Paradise',
    subtitle: 'More colors! Match 4 for Line Blasts!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'purple', 'orange'],
    maxMoves: 20,
    targetScore: 3200,
    targetType: 'score',
    starThresholds: [3200, 4200, 5600],
  },
  {
    id: 3,
    name: 'Jelly Jubilee',
    subtitle: 'Collect Pink Hearts & Blue Chills!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'purple', 'green'],
    maxMoves: 22,
    targetScore: 3000,
    targetType: 'collect_colors',
    targetGoals: { pink: 14, blue: 14 },
    starThresholds: [3000, 4200, 5800],
  },
  {
    id: 4,
    name: 'Iceberg Bounce',
    subtitle: 'Crack the frozen blocks with adjacent matches!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'orange'],
    maxMoves: 22,
    targetScore: 4000,
    targetType: 'break_ice',
    targetGoals: { ice: 8 },
    starThresholds: [4000, 5400, 7000],
    initialObstacles: [
      { row: 2, col: 2, type: 'ice' },
      { row: 2, col: 4, type: 'ice' },
      { row: 3, col: 3, type: 'ice' },
      { row: 4, col: 2, type: 'ice' },
      { row: 4, col: 4, type: 'ice' },
      { row: 1, col: 3, type: 'ice' },
      { row: 5, col: 3, type: 'ice' },
      { row: 3, col: 1, type: 'ice' },
    ],
  },
  {
    id: 5,
    name: 'Crate Kingdom',
    subtitle: 'Smash through sturdy toy crates!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'purple', 'green'],
    maxMoves: 22,
    targetScore: 5000,
    targetType: 'clear_crates',
    targetGoals: { crate: 8 },
    starThresholds: [5000, 6600, 8500],
    initialObstacles: [
      { row: 2, col: 3, type: 'crate', hp: 1 },
      { row: 3, col: 2, type: 'crate', hp: 1 },
      { row: 3, col: 4, type: 'crate', hp: 1 },
      { row: 4, col: 3, type: 'crate', hp: 1 },
      { row: 1, col: 1, type: 'crate', hp: 1 },
      { row: 1, col: 5, type: 'crate', hp: 1 },
      { row: 5, col: 1, type: 'crate', hp: 1 },
      { row: 5, col: 5, type: 'crate', hp: 1 },
    ],
  },
  {
    id: 6,
    name: 'Rainbow Carnival',
    subtitle: 'Assemble 6+ matches for legendary Color Blasts!',
    rows: 7,
    cols: 7,
    colors: ['yellow', 'pink', 'blue', 'purple', 'orange', 'green'],
    maxMoves: 24,
    targetScore: 7500,
    targetType: 'score',
    starThresholds: [7500, 9500, 12500],
  },
  {
    id: 7,
    name: 'Frozen Wonder',
    subtitle: 'Expanded 8x8 arena! Break 12 deep ice blocks!',
    rows: 8,
    cols: 8,
    colors: ['yellow', 'pink', 'blue', 'purple', 'orange'],
    maxMoves: 25,
    targetScore: 8500,
    targetType: 'break_ice',
    targetGoals: { ice: 12 },
    starThresholds: [8500, 11000, 14000],
    initialObstacles: [
      { row: 2, col: 2, type: 'ice' },
      { row: 2, col: 3, type: 'ice' },
      { row: 2, col: 4, type: 'ice' },
      { row: 2, col: 5, type: 'ice' },
      { row: 3, col: 2, type: 'ice' },
      { row: 3, col: 5, type: 'ice' },
      { row: 4, col: 2, type: 'ice' },
      { row: 4, col: 5, type: 'ice' },
      { row: 5, col: 2, type: 'ice' },
      { row: 5, col: 3, type: 'ice' },
      { row: 5, col: 4, type: 'ice' },
      { row: 5, col: 5, type: 'ice' },
    ],
  },
  {
    id: 8,
    name: 'Toy Master Summit',
    subtitle: 'The ultimate test of blocks, ice, crates & combos!',
    rows: 8,
    cols: 8,
    colors: ['yellow', 'pink', 'blue', 'purple', 'orange', 'green'],
    maxMoves: 26,
    targetScore: 12000,
    targetType: 'score',
    starThresholds: [12000, 15500, 19500],
    initialObstacles: [
      { row: 1, col: 3, type: 'ice' },
      { row: 1, col: 4, type: 'ice' },
      { row: 6, col: 3, type: 'ice' },
      { row: 6, col: 4, type: 'ice' },
      { row: 3, col: 1, type: 'crate', hp: 1 },
      { row: 4, col: 1, type: 'crate', hp: 1 },
      { row: 3, col: 6, type: 'crate', hp: 1 },
      { row: 4, col: 6, type: 'crate', hp: 1 },
      { row: 3, col: 3, type: 'ice' },
      { row: 3, col: 4, type: 'ice' },
      { row: 4, col: 3, type: 'ice' },
      { row: 4, col: 4, type: 'ice' },
    ],
  },
];
